#ifndef READANDWRITECAFFEMODEL_PROCESSFUNCTION_H
#define READANDWRITECAFFEMODEL_PROCESSFUNCTION_H

float myProcessFunction(float thisData, float power);

#endif //READANDWRITECAFFEMODEL_PROCESSFUNCTION_H
